### ISSUE TITLE
Relations like "<", "<=", ">" and ">=" doesn't work for numbers/number strings

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu-Store-MongoDB#11]
Relations like "<", "<=", ">" and ">=" doesn't work for numbers/number strings:

catmandu.yml:

```yaml
---
store:
  cql:
    package: MongoDB
    options:
      database_name: camel
      bags:
        data:
          cql_mapping:
            default_index: all
            indexes:
              year:
                op:
                  'any': true
                  'all': true
                  '=': true
                  '>': true
                  '>=': true
                  '<': true
                  '<=': true
                  'exact': true
                field: 'year'
...
```

Store records:

```
$ catmandu import -v MARC --fix 'marc_map(260c,year);replace_all(year,"\D","");remove_field(record)' to MongoDB --database_name camel < camel.mrc 
```

Export records:

```
$ catmandu export -v cql --cql-query 'year < 2000' to YAML
exported 0 items
done
```

~Fix: Delete 'trick' in /Catmandu/Store/MongoDB/CQL.pm, line [137](https://github.com/LibreCat/Catmandu-Store-MongoDB/blob/master/lib/Catmandu/Store/MongoDB/CQL.pm#L137)~

```perl
...
# trick to force numeric values interpreted as integers
# $term = $term + 0 if ($term =~ /^[1-9]\d*$/);
...
```

```
$ catmandu -I ./fix export -v cql --cql-query 'year < 2000' to YAML
---
_id: 'fol05843555 '
year: '1999'
...
---
_id: 'fol05843579 '
year: '1999'
...
---
_id: 'fol05872355 '
year: '1999'
...
exported 3 items
done
```

Can someone please cross check this?
